name: Robert ÆOLUS Myers
favicon: null
layout_spectrum: 0.96844
typography_spectrum: 0.52032
title: Robert ÆOLUS Myers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffdff'
    - '#040507'
    - '#ccc5bf'
    - '#7f7774'
    - '#27569e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose:
  - name: null
    item: null
    url: null
