typography_spectrum: 1
color:
  brandColors:
    - '#06b6f2'
    - '#035ac3'
    - '#0a1b39'
    - '#f9f9f1'
    - '#47f6f2'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.6875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.35798
analytics:
  google: UA-74172439-1
  facebook: null
  twitter: null
name: Robert ÆOLUS Myers
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Robert ÆOLUS Myers
description: 'composer/arranger, multi-instrumentalist, and producer'
purpose: []
