analytics: {}
color:
  brandColors:
    - '#C8B0B0'
    - '#000000'
    - '#786060'
    - '#000000'
    - '#000000'
  brandStrength: 0.529279
  lightness: 0.188063
  rhythmicContrast: 0.252252
  saturation: 0.009473
cta: {}
layout_spectrum: 0
name: Robert ÆOLUS Myers
opengraph: {}
purpose: {}
typography_spectrum: 0.71509
