name: Robert ÆOLUS Myers
favicon: null
layout_spectrum: 0.24562
typography_spectrum: 0.52032
title: Robert ÆOLUS Myers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#06b6f2'
    - '#035ac3'
    - '#0a1b39'
    - '#f9f9f1'
    - '#47f6f2'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0
purpose:
  - name: null
    item: null
    url: null
