analytics:
  google: UA-74172439-1
color:
  brandColors:
    - '#06b6f2'
    - '#035ac3'
    - '#0a1b39'
    - '#f9f9f1'
    - '#47f6f2'
  brandStrength: 0
  lightness: 0.5
  rhythmicContrast: 0.5
  saturation: 0.6875
cta: {}
layout_spectrum: 1
name: Robert ÆOLUS Myers
opengraph: {}
purpose:
  - {}
typography_spectrum: 1
