analytics: {}
color:
  brandColors:
    - '#B0B8C8'
    - '#284058'
    - '#607898'
    - '#5080AF'
    - '#000000'
  brandStrength: 0.529279
  lightness: 0.617117
  rhythmicContrast: 0.753378
  saturation: 0.009473
cta: {}
layout_spectrum: 0.34154646931000265
name: Robert ÆOLUS Myers
opengraph: {}
purpose: {}
typography_spectrum: 0.605856
