typography_spectrum: 0.051502140471711755
color:
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  brandStrength: 0.17337328870780766
  lightness: 0.00983968679793179
  saturation: 0.2223825177643448
  rhythmicContrast: 0.5428148792125285
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.018189494032412767
analytics:
  google: UA-74172439-1
  facebook: null
  twitter: null
name: Robert ÆOLUS Myers
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Contact
    id: 2353bab1-09a5-499e-81b7-023eb6d51c8b
    type: content
  - name: THE MAGICIAN
    id: 8ff0325d-b10a-4cd6-ba6b-4b54d9bdf340
    type: content
  - name: Collected Works
    id: 789e3563-970c-488d-933c-a0799547bcab
    type: content
  - name: About
    id: c02a5e58-3ce8-47ec-b08e-5b9c55a72a83
    type: content
favicon: null
title: Robert ÆOLUS Myers
description: 'composer/arranger, multi-instrumentalist, recording artist, and producer'
purpose: []
