layout_spectrum: 0.018189494032412767
typography_spectrum: 0.9212800071109086
color:
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  brandStrength: 0.17337328870780766
  lightness: 0.00983968679793179
  saturation: 0.2223825177643448
  rhythmicContrast: 0.5428148792125285
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-74172439-1
  facebook: null
  twitter: null
name: Robert ÆOLUS Myers
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: wikipedia
    url: 'https://en.wikipedia.org/wiki/Robert_%C3%86OLUS_Myers'
    type: external
  - name: Contact
    id: 5f448283-5a85-4c18-8c50-240deb9e4815
    type: content
favicon: null
title: Robert ÆOLUS Myers
description: 'composer/arranger, multi-instrumentalist, recording artist, and producer'
purpose: []
