name: Robert ÆOLUS Myers
favicon: null
layout_spectrum: 0.77187
typography_spectrum: 0.52032
title: Robert ÆOLUS Myers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1e4eb'
    - '#1d1b28'
    - '#41434f'
    - '#5c5c68'
    - '#809375'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.252252
purpose:
  - name: null
    item: null
    url: null
